"""add extracted text to documents

Revision ID: 49e39dc19262
Revises: b336b96cc969
Create Date: 2026-09-20 21:59:55.002103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49e39dc19262'
down_revision: Union[str, Sequence[str], None] = 'b336b96cc969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extracted_text')
    # ### end Alembic commands ###
